import { FormEvent, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import type { Horse, Organization } from '../types'

type Option = { value: string; label: string }
type Field = { key: string; label: string; type?: 'text'|'number'|'date'|'datetime-local'|'textarea'|'select'; required?: boolean; options?: Option[]; placeholder?: string; step?: string }
type Column = { key: string; label: string; render?: (value: unknown, row: Record<string, unknown>) => string }
type Config = { table: string; title: string; eyebrow: string; description: string; singular: string; fields: Field[]; columns: Column[]; defaults: Record<string, unknown>; order: string; ascending?: boolean }

const labels: Record<string,string> = { stall:'Baia',paddock:'Piquete',pasture:'Pasto',quarantine:'Quarentena',other:'Outro',pending:'Pendente',scheduled:'Agendado',completed:'Concluído',cancelled:'Cancelado',hay:'Feno',feed:'Ração',supplement:'Suplemento',medicine:'Medicamento',material:'Material',expense:'Despesa',income:'Receita',paid:'Pago',overdue:'Atrasado' }
const text = (value: unknown) => labels[String(value)] ?? String(value ?? '—')
const date = (value: unknown) => value ? new Date(String(value).length === 10 ? `${value}T12:00:00` : String(value)).toLocaleDateString('pt-BR') : '—'
const money = (value: unknown) => Number(value ?? 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

function CrudModule({ organization, canEdit, config }: { organization: Organization; canEdit: boolean; config: Config }) {
  const [rows,setRows]=useState<Record<string,unknown>[]>([])
  const [form,setForm]=useState<Record<string,unknown>>(config.defaults)
  const [editing,setEditing]=useState<string|null>(null)
  const [open,setOpen]=useState(false)
  const [message,setMessage]=useState('')
  async function load(){ if(!supabase)return; const {data,error}=await supabase.from(config.table).select('*').eq('organization_id',organization.id).order(config.order,{ascending:config.ascending??false}); if(error)setMessage(error.message); else setRows((data??[]) as Record<string,unknown>[]) }
  useEffect(()=>{void load()},[organization.id,config.table])
  function startNew(){setEditing(null);setForm(config.defaults);setOpen(true);setMessage('')}
  function startEdit(row:Record<string,unknown>){setEditing(String(row.id));const values={...config.defaults};config.fields.forEach(f=>values[f.key]=row[f.key]??'');setForm(values);setOpen(true)}
  async function save(e:FormEvent){e.preventDefault();if(!supabase)return;const payload:Record<string,unknown>={...form,organization_id:organization.id};config.fields.forEach(f=>{if(payload[f.key]==='')payload[f.key]=null;if(f.type==='number'&&payload[f.key]!=null)payload[f.key]=Number(payload[f.key])});const query=editing?supabase.from(config.table).update(payload).eq('id',editing):supabase.from(config.table).insert(payload);const {error}=await query;if(error)setMessage(error.message);else{setOpen(false);await load()}}
  async function remove(row:Record<string,unknown>){if(!supabase||!confirm(`Excluir este registro de ${config.singular}?`))return;const{error}=await supabase.from(config.table).delete().eq('id',row.id);if(error)setMessage(error.message);else await load()}
  return <section className="content operations-page"><div className="page-heading"><div><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p>{config.description}</p></div>{canEdit&&<button className="primary-button" onClick={startNew}>＋ Novo registro</button>}</div>{message&&<p className="form-message">{message}</p>}<div className="panel table-panel"><div className="responsive-table"><table><thead><tr>{config.columns.map(c=><th key={c.key}>{c.label}</th>)}{canEdit&&<th></th>}</tr></thead><tbody>{rows.map(row=><tr key={String(row.id)}>{config.columns.map(c=><td key={c.key}>{c.render?c.render(row[c.key],row):text(row[c.key])}</td>)}{canEdit&&<td><div className="row-actions"><button onClick={()=>startEdit(row)}>Editar</button><button className="danger" onClick={()=>remove(row)}>Excluir</button></div></td>}</tr>)}{!rows.length&&<tr><td colSpan={config.columns.length+1} className="empty-state">Nenhum registro. Adicione o primeiro para começar.</td></tr>}</tbody></table></div></div>
  {open&&<div className="modal"><form className="modal-card operation-form" onSubmit={save}><button type="button" className="modal-close" onClick={()=>setOpen(false)}>×</button><p className="eyebrow">{config.eyebrow}</p><h2>{editing?'Editar':'Novo'} {config.singular}</h2><div className="dynamic-form">{config.fields.map(f=><label key={f.key}>{f.label}{f.type==='textarea'?<textarea value={String(form[f.key]??'')} required={f.required} placeholder={f.placeholder} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:f.type==='select'?<select value={String(form[f.key]??'')} required={f.required} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">Selecione</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input type={f.type??'text'} step={f.step} value={String(form[f.key]??'')} required={f.required} placeholder={f.placeholder} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}</div><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button">Salvar</button></div></form></div>}</section>
}

export function Facilities({organization,canEdit,horses}:{organization:Organization;canEdit:boolean;horses:Horse[]}){
 const horseOptions=horses.map(h=>({value:h.id,label:h.name}));const config=useMemo<Config>(()=>({table:'facilities',title:'Baias e piquetes',eyebrow:'INSTALAÇÕES',description:'Controle ocupação, capacidade e situação dos espaços.',singular:'espaço',order:'name',ascending:true,defaults:{name:'',type:'stall',capacity:1,current_horse_id:'',notes:''},fields:[{key:'name',label:'Nome',required:true},{key:'type',label:'Tipo',type:'select',required:true,options:[{value:'stall',label:'Baia'},{value:'paddock',label:'Piquete'},{value:'pasture',label:'Pasto'},{value:'quarantine',label:'Quarentena'},{value:'other',label:'Outro'}]},{key:'capacity',label:'Capacidade',type:'number',required:true},{key:'current_horse_id',label:'Animal ocupante',type:'select',options:horseOptions},{key:'notes',label:'Observações',type:'textarea'}],columns:[{key:'name',label:'Espaço'},{key:'type',label:'Tipo'},{key:'capacity',label:'Capacidade'},{key:'current_horse_id',label:'Ocupante',render:v=>horses.find(h=>h.id===v)?.name??'Livre'}]}),[horses]);return <CrudModule {...{organization,canEdit,config}}/>
}

export function Health({organization,canEdit,horses}:{organization:Organization;canEdit:boolean;horses:Horse[]}){
 const horseOptions=horses.map(h=>({value:h.id,label:h.name}));const config=useMemo<Config>(()=>({table:'health_records',title:'Saúde e manejo',eyebrow:'PRONTUÁRIO',description:'Vacinas, medicamentos, consultas, casqueamento e ferrageamento.',singular:'procedimento',order:'event_date',defaults:{horse_id:'',record_type:'Vacina',title:'',event_date:new Date().toISOString().slice(0,10),next_due_date:'',professional:'',cost:0,status:'completed',notes:''},fields:[{key:'horse_id',label:'Animal',type:'select',options:horseOptions},{key:'record_type',label:'Tipo',required:true,placeholder:'Vacina, consulta, casqueamento…'},{key:'title',label:'Procedimento',required:true},{key:'event_date',label:'Data',type:'date',required:true},{key:'next_due_date',label:'Próximo vencimento',type:'date'},{key:'professional',label:'Profissional'},{key:'cost',label:'Custo',type:'number',step:'0.01'},{key:'status',label:'Situação',type:'select',required:true,options:[{value:'pending',label:'Pendente'},{value:'scheduled',label:'Agendado'},{value:'completed',label:'Concluído'},{value:'cancelled',label:'Cancelado'}]},{key:'notes',label:'Observações',type:'textarea'}],columns:[{key:'event_date',label:'Data',render:date},{key:'title',label:'Procedimento'},{key:'horse_id',label:'Animal',render:v=>horses.find(h=>h.id===v)?.name??'Plantel'},{key:'next_due_date',label:'Próximo',render:date},{key:'cost',label:'Custo',render:money},{key:'status',label:'Situação'}]}),[horses]);return <CrudModule {...{organization,canEdit,config}}/>
}

export function Tasks({organization,canEdit,horses}:{organization:Organization;canEdit:boolean;horses:Horse[]}){
 const config=useMemo<Config>(()=>({table:'tasks',title:'Agenda e tarefas',eyebrow:'ROTINA',description:'Organize responsáveis, prazos e atividades recorrentes.',singular:'tarefa',order:'due_at',ascending:true,defaults:{title:'',category:'Geral',due_at:new Date().toISOString().slice(0,16),assigned_name:'',horse_id:'',status:'pending',recurrence:'',notes:''},fields:[{key:'title',label:'Tarefa',required:true},{key:'category',label:'Categoria',required:true},{key:'due_at',label:'Data e horário',type:'datetime-local',required:true},{key:'assigned_name',label:'Responsável'},{key:'horse_id',label:'Animal',type:'select',options:horses.map(h=>({value:h.id,label:h.name}))},{key:'status',label:'Situação',type:'select',required:true,options:[{value:'pending',label:'Pendente'},{value:'scheduled',label:'Agendada'},{value:'completed',label:'Concluída'},{value:'cancelled',label:'Cancelada'}]},{key:'recurrence',label:'Recorrência',placeholder:'Ex.: semanal, a cada 45 dias'},{key:'notes',label:'Observações',type:'textarea'}],columns:[{key:'due_at',label:'Prazo',render:date},{key:'title',label:'Tarefa'},{key:'category',label:'Categoria'},{key:'assigned_name',label:'Responsável'},{key:'status',label:'Situação'}]}),[horses]);return <CrudModule {...{organization,canEdit,config}}/>
}

export function Finance({organization,canEdit,horses}:{organization:Organization;canEdit:boolean;horses:Horse[]}){
 const config=useMemo<Config>(()=>({table:'financial_entries',title:'Financeiro',eyebrow:'CUSTOS E RECEITAS',description:'Acompanhe despesas, receitas, fornecedores e custos por animal.',singular:'lançamento',order:'due_date',defaults:{entry_type:'expense',category:'',description:'',amount:'',due_date:new Date().toISOString().slice(0,10),paid_date:'',status:'pending',supplier:'',horse_id:'',notes:''},fields:[{key:'entry_type',label:'Tipo',type:'select',required:true,options:[{value:'expense',label:'Despesa'},{value:'income',label:'Receita'}]},{key:'category',label:'Categoria',required:true},{key:'description',label:'Descrição',required:true},{key:'amount',label:'Valor',type:'number',step:'0.01',required:true},{key:'due_date',label:'Vencimento',type:'date',required:true},{key:'paid_date',label:'Pagamento',type:'date'},{key:'status',label:'Situação',type:'select',required:true,options:[{value:'pending',label:'Pendente'},{value:'paid',label:'Pago'},{value:'overdue',label:'Atrasado'},{value:'cancelled',label:'Cancelado'}]},{key:'supplier',label:'Fornecedor / cliente'},{key:'horse_id',label:'Animal relacionado',type:'select',options:horses.map(h=>({value:h.id,label:h.name}))},{key:'notes',label:'Observações',type:'textarea'}],columns:[{key:'due_date',label:'Vencimento',render:date},{key:'description',label:'Descrição'},{key:'entry_type',label:'Tipo'},{key:'category',label:'Categoria'},{key:'amount',label:'Valor',render:money},{key:'status',label:'Situação'}]}),[horses]);return <CrudModule {...{organization,canEdit,config}}/>
}

export function Inventory({organization,canEdit}:{organization:Organization;canEdit:boolean}){
 const config:Config={table:'inventory_items',title:'Estoque e alimentação',eyebrow:'INSUMOS',description:'Controle feno, ração, suplementos, medicamentos e materiais.',singular:'item',order:'name',ascending:true,defaults:{name:'',category:'feed',unit:'kg',current_stock:0,minimum_stock:0,unit_cost:0,supplier:'',expires_at:''},fields:[{key:'name',label:'Item',required:true},{key:'category',label:'Categoria',type:'select',required:true,options:[{value:'hay',label:'Feno'},{value:'feed',label:'Ração'},{value:'supplement',label:'Suplemento'},{value:'medicine',label:'Medicamento'},{value:'material',label:'Material'},{value:'other',label:'Outro'}]},{key:'unit',label:'Unidade',required:true},{key:'current_stock',label:'Estoque atual',type:'number',step:'0.001',required:true},{key:'minimum_stock',label:'Estoque mínimo',type:'number',step:'0.001',required:true},{key:'unit_cost',label:'Custo unitário',type:'number',step:'0.01'},{key:'supplier',label:'Fornecedor'},{key:'expires_at',label:'Validade',type:'date'}],columns:[{key:'name',label:'Item'},{key:'category',label:'Categoria'},{key:'current_stock',label:'Estoque',render:(v,r)=>`${v} ${r.unit}`},{key:'minimum_stock',label:'Mínimo',render:(v,r)=>`${v} ${r.unit}`},{key:'unit_cost',label:'Custo unitário',render:money},{key:'expires_at',label:'Validade',render:date}]};return <CrudModule {...{organization,canEdit,config}}/>
}
