import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

interface ClientRow { id:string; name:string; city:string|null; state:string|null; created_at:string; memberships:{count:number}[]; horses:{count:number}[]; subscriptions:{status:string; plans:{name:string;price_cents:number}|null}[] }

export function PlatformAdmin({ userName, hasHaras, onOpenHaras, onCreateHaras }: { userName: string; hasHaras: boolean; onOpenHaras: () => void; onCreateHaras: () => void }) {
  const [clients,setClients]=useState<ClientRow[]>([])
  const [message,setMessage]=useState('')
  useEffect(()=>{ if(!supabase)return; supabase.from('organizations').select('id,name,city,state,created_at,memberships(count),horses(count),subscriptions(status,plans(name,price_cents))').order('created_at',{ascending:false}).then(({data,error})=>{if(error)setMessage(error.message);else setClients((data??[]) as unknown as ClientRow[])}) },[])
  const active=clients.filter(c=>c.subscriptions?.[0]?.status==='active').length
  const monthly=clients.reduce((sum,c)=>c.subscriptions?.[0]?.status==='active'?sum+(c.subscriptions[0].plans?.price_cents??0):sum,0)
  return <div className="platform-shell"><header className="platform-top"><div className="auth-logo"><span className="brand-mark">GM</span><span>Genuína <strong>Marcha</strong></span></div><div className="platform-actions"><button className="context-switch" onClick={hasHaras ? onOpenHaras : onCreateHaras}>♞ {hasHaras ? 'Acessar meu haras' : 'Criar haras de demonstração'}</button><span className="admin-badge">ADMINISTRAÇÃO DA PLATAFORMA</span><button className="signout" onClick={()=>supabase?.auth.signOut()}>Sair</button></div></header><main className="platform-content">
    <div className="page-heading"><div><p className="eyebrow">PAINEL DO PROPRIETÁRIO</p><h1>Olá, {userName.split(' ')[0]}.</h1><p>Visão comercial e operacional de todos os clientes.</p></div><button className="primary-button" onClick={hasHaras ? onOpenHaras : onCreateHaras}>{hasHaras ? '♞ Gerenciar meu haras' : '＋ Criar haras de demonstração'}</button></div>
    <div className="metrics"><article className="metric"><div className="metric-icon green">▦</div><div><span>Haras cadastrados</span><strong>{clients.length}</strong><small>Base total de clientes</small></div></article><article className="metric"><div className="metric-icon gold">◆</div><div><span>Assinaturas ativas</span><strong>{active}</strong><small>Clientes pagantes</small></div></article><article className="metric"><div className="metric-icon blue">♞</div><div><span>Animais gerenciados</span><strong>{clients.reduce((s,c)=>s+(c.horses?.[0]?.count??0),0)}</strong><small>Em toda a plataforma</small></div></article><article className="metric"><div className="metric-icon rose">R$</div><div><span>Receita mensal</span><strong>{(monthly/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><small>Receita recorrente estimada</small></div></article></div>
    {message&&<p className="form-message">{message}</p>}<section className="panel table-panel"><div className="panel-heading admin-table-heading"><div><span className="section-tag">CLIENTES</span><h2>Haras da plataforma</h2></div></div><div className="responsive-table"><table><thead><tr><th>Haras</th><th>Localização</th><th>Usuários</th><th>Animais</th><th>Plano</th><th>Situação</th></tr></thead><tbody>{clients.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>Desde {new Date(c.created_at).toLocaleDateString('pt-BR')}</small></td><td>{[c.city,c.state].filter(Boolean).join(' / ')||'—'}</td><td>{c.memberships?.[0]?.count??0}</td><td>{c.horses?.[0]?.count??0}</td><td>{c.subscriptions?.[0]?.plans?.name||'Sem plano'}</td><td><span className={`status ${c.subscriptions?.[0]?.status||'trial'}`}>{c.subscriptions?.[0]?.status||'avaliação'}</span></td></tr>)}{!clients.length&&<tr><td colSpan={6} className="empty-state">Nenhum cliente cadastrado ainda.</td></tr>}</tbody></table></div></section>
  </main></div>
}
