import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import type { Organization, Role } from '../types'

interface MemberRow { user_id:string; role:Role; status:string; profile:{full_name:string|null}|null }
interface InviteRow { id:string; email:string; role:Role; status:string; created_at:string }
const roleLabels:Record<Role,string>={owner:'Proprietário',admin:'Administrador',manager:'Gerente',staff:'Tratador',vet:'Veterinário',finance:'Financeiro',viewer:'Consulta'}

export function Team({organization,canEdit}:{organization:Organization;canEdit:boolean}){
 const [members,setMembers]=useState<MemberRow[]>([]);const[invites,setInvites]=useState<InviteRow[]>([]);const[email,setEmail]=useState('');const[role,setRole]=useState<Role>('staff');const[message,setMessage]=useState('')
 async function load(){if(!supabase)return;const[m,i]=await Promise.all([supabase.from('memberships').select('user_id,role,status,profile:profiles(full_name)').eq('organization_id',organization.id),supabase.from('team_invites').select('id,email,role,status,created_at').eq('organization_id',organization.id).order('created_at',{ascending:false})]);if(m.error)setMessage(m.error.message);else setMembers((m.data??[]) as unknown as MemberRow[]);if(i.error)setMessage(i.error.message);else setInvites((i.data??[]) as InviteRow[])}
 useEffect(()=>{void load()},[organization.id])
 async function invite(e:FormEvent){e.preventDefault();if(!supabase)return;const{error}=await supabase.from('team_invites').upsert({organization_id:organization.id,email:email.trim().toLowerCase(),role,status:'pending'},{onConflict:'organization_id,email'});if(error)setMessage(error.message);else{setEmail('');setMessage('Convite registrado. Oriente a pessoa a criar a conta com este mesmo e-mail.');await load()}}
 async function cancel(id:string){if(!supabase)return;await supabase.from('team_invites').update({status:'cancelled'}).eq('id',id);await load()}
 return <section className="content team-page"><div className="page-heading"><div><p className="eyebrow">EQUIPE E ACESSOS</p><h1>Usuários do haras</h1><p>Defina quem pode acessar e qual será a função de cada pessoa.</p></div></div>{message&&<p className="form-message success-message">{message}</p>}{canEdit&&<form className="panel invite-form" onSubmit={invite}><div><h2>Convidar usuário</h2><p>O acesso será vinculado quando a pessoa criar a conta com o e-mail informado.</p></div><label>E-mail<input type="email" value={email} required onChange={e=>setEmail(e.target.value)} placeholder="pessoa@email.com"/></label><label>Função<select value={role} onChange={e=>setRole(e.target.value as Role)}>{Object.entries(roleLabels).filter(([r])=>r!=='owner').map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="primary-button">Registrar convite</button></form>}
 <div className="panel table-panel"><div className="admin-table-heading"><p className="section-tag">ACESSOS ATIVOS</p><h2>Equipe</h2></div><div className="responsive-table"><table><thead><tr><th>Nome</th><th>Função</th><th>Situação</th></tr></thead><tbody>{members.map(m=><tr key={m.user_id}><td><strong>{m.profile?.full_name||'Usuário cadastrado'}</strong></td><td>{roleLabels[m.role]}</td><td><span className="status active">Ativo</span></td></tr>)}</tbody></table></div></div>
 {invites.some(i=>i.status==='pending')&&<div className="panel table-panel pending-invites"><div className="admin-table-heading"><p className="section-tag">CONVITES</p><h2>Aguardando cadastro</h2></div><div className="responsive-table"><table><thead><tr><th>E-mail</th><th>Função</th><th>Enviado</th><th></th></tr></thead><tbody>{invites.filter(i=>i.status==='pending').map(i=><tr key={i.id}><td>{i.email}</td><td>{roleLabels[i.role]}</td><td>{new Date(i.created_at).toLocaleDateString('pt-BR')}</td><td>{canEdit&&<button className="text-danger" onClick={()=>cancel(i.id)}>Cancelar</button>}</td></tr>)}</tbody></table></div></div>}
 </section>
}
